"""Assets bundled with capmd (Quick Action installer, etc.).

The `.shortcut` file shipped here is a binary plist consumed by macOS
Shortcuts.app.  It's a "source artifact" in the sense that `setup
quick-action` imports it into the user's Shortcuts library, but it's
generated by ``scripts/build-quick-action.py`` from this package's source
(not hand-built in Shortcuts.app).  See ``scripts/build-quick-action.py``
for how it's produced and how to iterate on its content.

Exposes :data:`SHORTCUT_RESOURCE` (a :class:`Traversable`) pointing at
``Convert capmd chapter.shortcut`` inside this package.
"""

from __future__ import annotations

from importlib.abc import Traversable
from importlib.resources import files

__all__ = ["SHORTCUT_NAME", "SHORTCUT_RESOURCE"]


SHORTCUT_NAME: str = "Convert capmd chapter"
"""Display name of the Quick Action (matches WFWorkflow name in the plist)."""

SHORTCUT_RESOURCE: Traversable = files(__name__).joinpath("Convert capmd chapter.shortcut")
"""Resource path to the shipped ``.shortcut`` binary plist.

Use :func:`importlib.resources.as_file` to materialize the resource on disk
when an external CLI (``shortcuts import``/``shortcuts sign``) needs a real
file path.
"""
