"""Compuestos hyphenados comunes que NO deben unirse.

Lista bundled (~150 entradas). Crece con el tiempo a medida que se
encuentran falsos positivos en libros reales.
"""

from __future__ import annotations

__all__ = ["COMPOUND_EXCEPTIONS"]

COMPOUND_EXCEPTIONS: frozenset[str] = frozenset(
    {
        # well-*
        "well-known",
        "well-defined",
        "well-formed",
        "well-being",
        "well-deserved",
        "well-documented",
        "well-structured",
        "well-designed",
        "well-tested",
        "well-written",
        "well-established",
        "well-aware",
        "well-intentioned",
        "well-meaning",
        "well-read",
        "well-spoken",
        "well-suited",
        "well-supported",
        "well-versed",
        "well-worth",
        # long- / short- / mid-
        "long-term",
        "long-lived",
        "long-standing",
        "long-running",
        "long-range",
        "long-lasting",
        "long-awaited",
        "long-distance",
        "long-time",
        "short-term",
        "short-lived",
        "short-range",
        "mid-term",
        "mid-range",
        # high- / low-
        "high-level",
        "low-level",
        "high-performance",
        "high-quality",
        "low-quality",
        "high-resolution",
        "high-speed",
        "high-energy",
        "low-energy",
        "low-cost",
        "low-latency",
        "high-latency",
        "high-throughput",
        "low-throughput",
        "high-end",
        "low-end",
        "high-priority",
        "high-order",
        "low-order",
        # self-
        "self-contained",
        "self-driving",
        "self-aware",
        "self-taught",
        "self-signed",
        "self-hosted",
        "self-managed",
        "self-paced",
        "self-service",
        "self-sustaining",
        "self-sufficient",
        "self-discipline",
        "self-esteem",
        "self-evident",
        "self-explanatory",
        "self-regulating",
        # non- / pre- / post- / re- / sub- / super- / over- / under-
        "non-functional",
        "non-blocking",
        "non-trivial",
        "non-empty",
        "non-zero",
        "pre-existing",
        "pre-built",
        "pre-configured",
        "pre-installed",
        "pre-loaded",
        "pre-defined",
        "pre-determined",
        "pre-requisite",
        "pre-release",
        "post-processing",
        "post-mortem",
        "post-operative",
        "post-script",
        "re-engineered",
        "re-enter",
        "re-evaluate",
        "sub-process",
        "sub-agent",
        "sub-tree",
        "sub-class",
        "sub-array",
        "super-user",
        "super-admin",
        "over-engineered",
        "over-constrained",
        "under-represented",
        # part-time / full-time / real-time
        "part-time",
        "full-time",
        "real-time",
        "down-time",
        "up-time",
        "run-time",
        "compile-time",
        "design-time",
        "build-time",
        "load-time",
        "start-up",
        # cost- / time- / labor-
        "cost-effective",
        "cost-efficient",
        "cost-of-living",
        "time-consuming",
        "time-dependent",
        "time-sensitive",
        "time-tested",
        "time-honored",
        "labor-intensive",
        "labor-saving",
        # -of-the-
        "state-of-the-art",
        "state-of-mind",
        "out-of-the-box",
        "mother-of-pearl",
        "man-of-war",
        "jack-of-all-trades",
        "lily-of-the-valley",
        "tip-of-the-iceberg",
        # in- / on- / off- / out- (legacy/historical)
        "in-line",
        "on-line",
        "off-line",
        "out-of-date",
        "out-of-bounds",
        "out-of-scope",
        "out-of-stock",
        "up-to-date",
        "up-to-the-minute",
        # compound adverbs / others
        "step-by-step",
        "side-by-side",
        "face-to-face",
        "back-to-back",
        "front-end",
        "back-end",
        # scientific / mathematical
        "open-source",
        "closed-form",
        "real-valued",
        "complex-valued",
    }
)
